[workspace]
changelog_update = true
publish = true
dependencies_update = true
semver_check = true
release_always = false

[[package]]
name = "tpack-core"
changelog_path = "crates/tpack-core/CHANGELOG.md"

[[package]]
name = "tpack-macros"
changelog_path = "crates/tpack-macros/CHANGELOG.md"

[[package]]
name = "tpack"
changelog_path = "crates/tpack/CHANGELOG.md"

[[package]]
name = "tpack-cli"
changelog_path = "crates/tpack-cli/CHANGELOG.md"
